# Generated by Django 4.2.8 on 2026-06-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='fee',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fee',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
    ]
